module.exports = {
  SUCCESS_STATUS_CODE: 200,
  CREATED_STATUS_CODE: 201,
  FOUND_STATUS_CODE: 300,
  MOVED_PERMANENTLY_STATUS_CODE: 301,
  BAD_REQUEST_ERROR_CODE: 400,
  UNAUTHORIZED_ERROR_CODE: 401,
  FORBIDDEN_ERROR_CODE: 403,
  NOT_FOUND_ERROR_CODE: 404,
  METHOD_NOT_ALLOWED_ERROR_CODE: 405,
  NOT_ACCEPTABLE_ERROR_CODE: 406,
  REQUEST_TIMEOUT_ERROR_CODE: 408,
  CONFLICT_ERROR_CODE: 409,
  INTERNAL_SERVER_ERROR_CODE: 500,

  VERIFIED: "verified",
  UNVERIFIED: "unverified",
  DELETED: "deleted",
  ACTIVE: "active"

};
